/*
AutoGlue API

API for managing K3s clusters across cloud providers

API version: dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autoglue

import (
	"encoding/json"
)

// checks if the DtoAttachCaptainDomainRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoAttachCaptainDomainRequest{}

// DtoAttachCaptainDomainRequest struct for DtoAttachCaptainDomainRequest
type DtoAttachCaptainDomainRequest struct {
	DomainId *string `json:"domain_id,omitempty"`
}

// NewDtoAttachCaptainDomainRequest instantiates a new DtoAttachCaptainDomainRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoAttachCaptainDomainRequest() *DtoAttachCaptainDomainRequest {
	this := DtoAttachCaptainDomainRequest{}
	return &this
}

// NewDtoAttachCaptainDomainRequestWithDefaults instantiates a new DtoAttachCaptainDomainRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoAttachCaptainDomainRequestWithDefaults() *DtoAttachCaptainDomainRequest {
	this := DtoAttachCaptainDomainRequest{}
	return &this
}

// GetDomainId returns the DomainId field value if set, zero value otherwise.
func (o *DtoAttachCaptainDomainRequest) GetDomainId() string {
	if o == nil || IsNil(o.DomainId) {
		var ret string
		return ret
	}
	return *o.DomainId
}

// GetDomainIdOk returns a tuple with the DomainId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoAttachCaptainDomainRequest) GetDomainIdOk() (*string, bool) {
	if o == nil || IsNil(o.DomainId) {
		return nil, false
	}
	return o.DomainId, true
}

// HasDomainId returns a boolean if a field has been set.
func (o *DtoAttachCaptainDomainRequest) HasDomainId() bool {
	if o != nil && !IsNil(o.DomainId) {
		return true
	}

	return false
}

// SetDomainId gets a reference to the given string and assigns it to the DomainId field.
func (o *DtoAttachCaptainDomainRequest) SetDomainId(v string) {
	o.DomainId = &v
}

func (o DtoAttachCaptainDomainRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoAttachCaptainDomainRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DomainId) {
		toSerialize["domain_id"] = o.DomainId
	}
	return toSerialize, nil
}

type NullableDtoAttachCaptainDomainRequest struct {
	value *DtoAttachCaptainDomainRequest
	isSet bool
}

func (v NullableDtoAttachCaptainDomainRequest) Get() *DtoAttachCaptainDomainRequest {
	return v.value
}

func (v *NullableDtoAttachCaptainDomainRequest) Set(val *DtoAttachCaptainDomainRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoAttachCaptainDomainRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoAttachCaptainDomainRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoAttachCaptainDomainRequest(val *DtoAttachCaptainDomainRequest) *NullableDtoAttachCaptainDomainRequest {
	return &NullableDtoAttachCaptainDomainRequest{value: val, isSet: true}
}

func (v NullableDtoAttachCaptainDomainRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoAttachCaptainDomainRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
