/*
AutoGlue API

API for managing K3s clusters across cloud providers

API version: dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autoglue

import (
	"encoding/json"
)

// checks if the HandlersVersionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HandlersVersionResponse{}

// HandlersVersionResponse struct for HandlersVersionResponse
type HandlersVersionResponse struct {
	Built      *string `json:"built,omitempty"`
	BuiltBy    *string `json:"builtBy,omitempty"`
	Commit     *string `json:"commit,omitempty"`
	CommitTime *string `json:"commitTime,omitempty"`
	Go         *string `json:"go,omitempty"`
	GoArch     *string `json:"goArch,omitempty"`
	GoOS       *string `json:"goOS,omitempty"`
	Modified   *bool   `json:"modified,omitempty"`
	Revision   *string `json:"revision,omitempty"`
	Vcs        *string `json:"vcs,omitempty"`
	Version    *string `json:"version,omitempty"`
}

// NewHandlersVersionResponse instantiates a new HandlersVersionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHandlersVersionResponse() *HandlersVersionResponse {
	this := HandlersVersionResponse{}
	return &this
}

// NewHandlersVersionResponseWithDefaults instantiates a new HandlersVersionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHandlersVersionResponseWithDefaults() *HandlersVersionResponse {
	this := HandlersVersionResponse{}
	return &this
}

// GetBuilt returns the Built field value if set, zero value otherwise.
func (o *HandlersVersionResponse) GetBuilt() string {
	if o == nil || IsNil(o.Built) {
		var ret string
		return ret
	}
	return *o.Built
}

// GetBuiltOk returns a tuple with the Built field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlersVersionResponse) GetBuiltOk() (*string, bool) {
	if o == nil || IsNil(o.Built) {
		return nil, false
	}
	return o.Built, true
}

// HasBuilt returns a boolean if a field has been set.
func (o *HandlersVersionResponse) HasBuilt() bool {
	if o != nil && !IsNil(o.Built) {
		return true
	}

	return false
}

// SetBuilt gets a reference to the given string and assigns it to the Built field.
func (o *HandlersVersionResponse) SetBuilt(v string) {
	o.Built = &v
}

// GetBuiltBy returns the BuiltBy field value if set, zero value otherwise.
func (o *HandlersVersionResponse) GetBuiltBy() string {
	if o == nil || IsNil(o.BuiltBy) {
		var ret string
		return ret
	}
	return *o.BuiltBy
}

// GetBuiltByOk returns a tuple with the BuiltBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlersVersionResponse) GetBuiltByOk() (*string, bool) {
	if o == nil || IsNil(o.BuiltBy) {
		return nil, false
	}
	return o.BuiltBy, true
}

// HasBuiltBy returns a boolean if a field has been set.
func (o *HandlersVersionResponse) HasBuiltBy() bool {
	if o != nil && !IsNil(o.BuiltBy) {
		return true
	}

	return false
}

// SetBuiltBy gets a reference to the given string and assigns it to the BuiltBy field.
func (o *HandlersVersionResponse) SetBuiltBy(v string) {
	o.BuiltBy = &v
}

// GetCommit returns the Commit field value if set, zero value otherwise.
func (o *HandlersVersionResponse) GetCommit() string {
	if o == nil || IsNil(o.Commit) {
		var ret string
		return ret
	}
	return *o.Commit
}

// GetCommitOk returns a tuple with the Commit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlersVersionResponse) GetCommitOk() (*string, bool) {
	if o == nil || IsNil(o.Commit) {
		return nil, false
	}
	return o.Commit, true
}

// HasCommit returns a boolean if a field has been set.
func (o *HandlersVersionResponse) HasCommit() bool {
	if o != nil && !IsNil(o.Commit) {
		return true
	}

	return false
}

// SetCommit gets a reference to the given string and assigns it to the Commit field.
func (o *HandlersVersionResponse) SetCommit(v string) {
	o.Commit = &v
}

// GetCommitTime returns the CommitTime field value if set, zero value otherwise.
func (o *HandlersVersionResponse) GetCommitTime() string {
	if o == nil || IsNil(o.CommitTime) {
		var ret string
		return ret
	}
	return *o.CommitTime
}

// GetCommitTimeOk returns a tuple with the CommitTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlersVersionResponse) GetCommitTimeOk() (*string, bool) {
	if o == nil || IsNil(o.CommitTime) {
		return nil, false
	}
	return o.CommitTime, true
}

// HasCommitTime returns a boolean if a field has been set.
func (o *HandlersVersionResponse) HasCommitTime() bool {
	if o != nil && !IsNil(o.CommitTime) {
		return true
	}

	return false
}

// SetCommitTime gets a reference to the given string and assigns it to the CommitTime field.
func (o *HandlersVersionResponse) SetCommitTime(v string) {
	o.CommitTime = &v
}

// GetGo returns the Go field value if set, zero value otherwise.
func (o *HandlersVersionResponse) GetGo() string {
	if o == nil || IsNil(o.Go) {
		var ret string
		return ret
	}
	return *o.Go
}

// GetGoOk returns a tuple with the Go field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlersVersionResponse) GetGoOk() (*string, bool) {
	if o == nil || IsNil(o.Go) {
		return nil, false
	}
	return o.Go, true
}

// HasGo returns a boolean if a field has been set.
func (o *HandlersVersionResponse) HasGo() bool {
	if o != nil && !IsNil(o.Go) {
		return true
	}

	return false
}

// SetGo gets a reference to the given string and assigns it to the Go field.
func (o *HandlersVersionResponse) SetGo(v string) {
	o.Go = &v
}

// GetGoArch returns the GoArch field value if set, zero value otherwise.
func (o *HandlersVersionResponse) GetGoArch() string {
	if o == nil || IsNil(o.GoArch) {
		var ret string
		return ret
	}
	return *o.GoArch
}

// GetGoArchOk returns a tuple with the GoArch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlersVersionResponse) GetGoArchOk() (*string, bool) {
	if o == nil || IsNil(o.GoArch) {
		return nil, false
	}
	return o.GoArch, true
}

// HasGoArch returns a boolean if a field has been set.
func (o *HandlersVersionResponse) HasGoArch() bool {
	if o != nil && !IsNil(o.GoArch) {
		return true
	}

	return false
}

// SetGoArch gets a reference to the given string and assigns it to the GoArch field.
func (o *HandlersVersionResponse) SetGoArch(v string) {
	o.GoArch = &v
}

// GetGoOS returns the GoOS field value if set, zero value otherwise.
func (o *HandlersVersionResponse) GetGoOS() string {
	if o == nil || IsNil(o.GoOS) {
		var ret string
		return ret
	}
	return *o.GoOS
}

// GetGoOSOk returns a tuple with the GoOS field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlersVersionResponse) GetGoOSOk() (*string, bool) {
	if o == nil || IsNil(o.GoOS) {
		return nil, false
	}
	return o.GoOS, true
}

// HasGoOS returns a boolean if a field has been set.
func (o *HandlersVersionResponse) HasGoOS() bool {
	if o != nil && !IsNil(o.GoOS) {
		return true
	}

	return false
}

// SetGoOS gets a reference to the given string and assigns it to the GoOS field.
func (o *HandlersVersionResponse) SetGoOS(v string) {
	o.GoOS = &v
}

// GetModified returns the Modified field value if set, zero value otherwise.
func (o *HandlersVersionResponse) GetModified() bool {
	if o == nil || IsNil(o.Modified) {
		var ret bool
		return ret
	}
	return *o.Modified
}

// GetModifiedOk returns a tuple with the Modified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlersVersionResponse) GetModifiedOk() (*bool, bool) {
	if o == nil || IsNil(o.Modified) {
		return nil, false
	}
	return o.Modified, true
}

// HasModified returns a boolean if a field has been set.
func (o *HandlersVersionResponse) HasModified() bool {
	if o != nil && !IsNil(o.Modified) {
		return true
	}

	return false
}

// SetModified gets a reference to the given bool and assigns it to the Modified field.
func (o *HandlersVersionResponse) SetModified(v bool) {
	o.Modified = &v
}

// GetRevision returns the Revision field value if set, zero value otherwise.
func (o *HandlersVersionResponse) GetRevision() string {
	if o == nil || IsNil(o.Revision) {
		var ret string
		return ret
	}
	return *o.Revision
}

// GetRevisionOk returns a tuple with the Revision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlersVersionResponse) GetRevisionOk() (*string, bool) {
	if o == nil || IsNil(o.Revision) {
		return nil, false
	}
	return o.Revision, true
}

// HasRevision returns a boolean if a field has been set.
func (o *HandlersVersionResponse) HasRevision() bool {
	if o != nil && !IsNil(o.Revision) {
		return true
	}

	return false
}

// SetRevision gets a reference to the given string and assigns it to the Revision field.
func (o *HandlersVersionResponse) SetRevision(v string) {
	o.Revision = &v
}

// GetVcs returns the Vcs field value if set, zero value otherwise.
func (o *HandlersVersionResponse) GetVcs() string {
	if o == nil || IsNil(o.Vcs) {
		var ret string
		return ret
	}
	return *o.Vcs
}

// GetVcsOk returns a tuple with the Vcs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlersVersionResponse) GetVcsOk() (*string, bool) {
	if o == nil || IsNil(o.Vcs) {
		return nil, false
	}
	return o.Vcs, true
}

// HasVcs returns a boolean if a field has been set.
func (o *HandlersVersionResponse) HasVcs() bool {
	if o != nil && !IsNil(o.Vcs) {
		return true
	}

	return false
}

// SetVcs gets a reference to the given string and assigns it to the Vcs field.
func (o *HandlersVersionResponse) SetVcs(v string) {
	o.Vcs = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *HandlersVersionResponse) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlersVersionResponse) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *HandlersVersionResponse) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *HandlersVersionResponse) SetVersion(v string) {
	o.Version = &v
}

func (o HandlersVersionResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HandlersVersionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Built) {
		toSerialize["built"] = o.Built
	}
	if !IsNil(o.BuiltBy) {
		toSerialize["builtBy"] = o.BuiltBy
	}
	if !IsNil(o.Commit) {
		toSerialize["commit"] = o.Commit
	}
	if !IsNil(o.CommitTime) {
		toSerialize["commitTime"] = o.CommitTime
	}
	if !IsNil(o.Go) {
		toSerialize["go"] = o.Go
	}
	if !IsNil(o.GoArch) {
		toSerialize["goArch"] = o.GoArch
	}
	if !IsNil(o.GoOS) {
		toSerialize["goOS"] = o.GoOS
	}
	if !IsNil(o.Modified) {
		toSerialize["modified"] = o.Modified
	}
	if !IsNil(o.Revision) {
		toSerialize["revision"] = o.Revision
	}
	if !IsNil(o.Vcs) {
		toSerialize["vcs"] = o.Vcs
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableHandlersVersionResponse struct {
	value *HandlersVersionResponse
	isSet bool
}

func (v NullableHandlersVersionResponse) Get() *HandlersVersionResponse {
	return v.value
}

func (v *NullableHandlersVersionResponse) Set(val *HandlersVersionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableHandlersVersionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableHandlersVersionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHandlersVersionResponse(val *HandlersVersionResponse) *NullableHandlersVersionResponse {
	return &NullableHandlersVersionResponse{value: val, isSet: true}
}

func (v NullableHandlersVersionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHandlersVersionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
