/*
AutoGlue API

API for managing K3s clusters across cloud providers

API version: dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autoglue

import (
	"encoding/json"
)

// checks if the DtoCredentialOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoCredentialOut{}

// DtoCredentialOut struct for DtoCredentialOut
type DtoCredentialOut struct {
	AccountId          *string                `json:"account_id,omitempty"`
	CreatedAt          *string                `json:"created_at,omitempty"`
	CredentialProvider *string                `json:"credential_provider,omitempty"`
	Id                 *string                `json:"id,omitempty"`
	Kind               *string                `json:"kind,omitempty"`
	Name               *string                `json:"name,omitempty"`
	Region             *string                `json:"region,omitempty"`
	SchemaVersion      *int32                 `json:"schema_version,omitempty"`
	Scope              map[string]interface{} `json:"scope,omitempty"`
	ScopeKind          *string                `json:"scope_kind,omitempty"`
	ScopeVersion       *int32                 `json:"scope_version,omitempty"`
	UpdatedAt          *string                `json:"updated_at,omitempty"`
}

// NewDtoCredentialOut instantiates a new DtoCredentialOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoCredentialOut() *DtoCredentialOut {
	this := DtoCredentialOut{}
	return &this
}

// NewDtoCredentialOutWithDefaults instantiates a new DtoCredentialOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoCredentialOutWithDefaults() *DtoCredentialOut {
	this := DtoCredentialOut{}
	return &this
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *DtoCredentialOut) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCredentialOut) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *DtoCredentialOut) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *DtoCredentialOut) SetAccountId(v string) {
	o.AccountId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *DtoCredentialOut) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCredentialOut) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *DtoCredentialOut) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *DtoCredentialOut) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetCredentialProvider returns the CredentialProvider field value if set, zero value otherwise.
func (o *DtoCredentialOut) GetCredentialProvider() string {
	if o == nil || IsNil(o.CredentialProvider) {
		var ret string
		return ret
	}
	return *o.CredentialProvider
}

// GetCredentialProviderOk returns a tuple with the CredentialProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCredentialOut) GetCredentialProviderOk() (*string, bool) {
	if o == nil || IsNil(o.CredentialProvider) {
		return nil, false
	}
	return o.CredentialProvider, true
}

// HasCredentialProvider returns a boolean if a field has been set.
func (o *DtoCredentialOut) HasCredentialProvider() bool {
	if o != nil && !IsNil(o.CredentialProvider) {
		return true
	}

	return false
}

// SetCredentialProvider gets a reference to the given string and assigns it to the CredentialProvider field.
func (o *DtoCredentialOut) SetCredentialProvider(v string) {
	o.CredentialProvider = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DtoCredentialOut) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCredentialOut) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DtoCredentialOut) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DtoCredentialOut) SetId(v string) {
	o.Id = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *DtoCredentialOut) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCredentialOut) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *DtoCredentialOut) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *DtoCredentialOut) SetKind(v string) {
	o.Kind = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DtoCredentialOut) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCredentialOut) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DtoCredentialOut) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DtoCredentialOut) SetName(v string) {
	o.Name = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *DtoCredentialOut) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCredentialOut) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *DtoCredentialOut) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *DtoCredentialOut) SetRegion(v string) {
	o.Region = &v
}

// GetSchemaVersion returns the SchemaVersion field value if set, zero value otherwise.
func (o *DtoCredentialOut) GetSchemaVersion() int32 {
	if o == nil || IsNil(o.SchemaVersion) {
		var ret int32
		return ret
	}
	return *o.SchemaVersion
}

// GetSchemaVersionOk returns a tuple with the SchemaVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCredentialOut) GetSchemaVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.SchemaVersion) {
		return nil, false
	}
	return o.SchemaVersion, true
}

// HasSchemaVersion returns a boolean if a field has been set.
func (o *DtoCredentialOut) HasSchemaVersion() bool {
	if o != nil && !IsNil(o.SchemaVersion) {
		return true
	}

	return false
}

// SetSchemaVersion gets a reference to the given int32 and assigns it to the SchemaVersion field.
func (o *DtoCredentialOut) SetSchemaVersion(v int32) {
	o.SchemaVersion = &v
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *DtoCredentialOut) GetScope() map[string]interface{} {
	if o == nil || IsNil(o.Scope) {
		var ret map[string]interface{}
		return ret
	}
	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCredentialOut) GetScopeOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Scope) {
		return map[string]interface{}{}, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *DtoCredentialOut) HasScope() bool {
	if o != nil && !IsNil(o.Scope) {
		return true
	}

	return false
}

// SetScope gets a reference to the given map[string]interface{} and assigns it to the Scope field.
func (o *DtoCredentialOut) SetScope(v map[string]interface{}) {
	o.Scope = v
}

// GetScopeKind returns the ScopeKind field value if set, zero value otherwise.
func (o *DtoCredentialOut) GetScopeKind() string {
	if o == nil || IsNil(o.ScopeKind) {
		var ret string
		return ret
	}
	return *o.ScopeKind
}

// GetScopeKindOk returns a tuple with the ScopeKind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCredentialOut) GetScopeKindOk() (*string, bool) {
	if o == nil || IsNil(o.ScopeKind) {
		return nil, false
	}
	return o.ScopeKind, true
}

// HasScopeKind returns a boolean if a field has been set.
func (o *DtoCredentialOut) HasScopeKind() bool {
	if o != nil && !IsNil(o.ScopeKind) {
		return true
	}

	return false
}

// SetScopeKind gets a reference to the given string and assigns it to the ScopeKind field.
func (o *DtoCredentialOut) SetScopeKind(v string) {
	o.ScopeKind = &v
}

// GetScopeVersion returns the ScopeVersion field value if set, zero value otherwise.
func (o *DtoCredentialOut) GetScopeVersion() int32 {
	if o == nil || IsNil(o.ScopeVersion) {
		var ret int32
		return ret
	}
	return *o.ScopeVersion
}

// GetScopeVersionOk returns a tuple with the ScopeVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCredentialOut) GetScopeVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.ScopeVersion) {
		return nil, false
	}
	return o.ScopeVersion, true
}

// HasScopeVersion returns a boolean if a field has been set.
func (o *DtoCredentialOut) HasScopeVersion() bool {
	if o != nil && !IsNil(o.ScopeVersion) {
		return true
	}

	return false
}

// SetScopeVersion gets a reference to the given int32 and assigns it to the ScopeVersion field.
func (o *DtoCredentialOut) SetScopeVersion(v int32) {
	o.ScopeVersion = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *DtoCredentialOut) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCredentialOut) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *DtoCredentialOut) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *DtoCredentialOut) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

func (o DtoCredentialOut) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoCredentialOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountId) {
		toSerialize["account_id"] = o.AccountId
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.CredentialProvider) {
		toSerialize["credential_provider"] = o.CredentialProvider
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if !IsNil(o.SchemaVersion) {
		toSerialize["schema_version"] = o.SchemaVersion
	}
	if !IsNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	if !IsNil(o.ScopeKind) {
		toSerialize["scope_kind"] = o.ScopeKind
	}
	if !IsNil(o.ScopeVersion) {
		toSerialize["scope_version"] = o.ScopeVersion
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableDtoCredentialOut struct {
	value *DtoCredentialOut
	isSet bool
}

func (v NullableDtoCredentialOut) Get() *DtoCredentialOut {
	return v.value
}

func (v *NullableDtoCredentialOut) Set(val *DtoCredentialOut) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoCredentialOut) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoCredentialOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoCredentialOut(val *DtoCredentialOut) *NullableDtoCredentialOut {
	return &NullableDtoCredentialOut{value: val, isSet: true}
}

func (v NullableDtoCredentialOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoCredentialOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
