/*
AutoGlue API

API for managing K3s clusters across cloud providers

API version: dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autoglue

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// GetSSHKey200Response - struct for GetSSHKey200Response
type GetSSHKey200Response struct {
	DtoSshResponse       *DtoSshResponse
	DtoSshRevealResponse *DtoSshRevealResponse
}

// DtoSshResponseAsGetSSHKey200Response is a convenience function that returns DtoSshResponse wrapped in GetSSHKey200Response
func DtoSshResponseAsGetSSHKey200Response(v *DtoSshResponse) GetSSHKey200Response {
	return GetSSHKey200Response{
		DtoSshResponse: v,
	}
}

// DtoSshRevealResponseAsGetSSHKey200Response is a convenience function that returns DtoSshRevealResponse wrapped in GetSSHKey200Response
func DtoSshRevealResponseAsGetSSHKey200Response(v *DtoSshRevealResponse) GetSSHKey200Response {
	return GetSSHKey200Response{
		DtoSshRevealResponse: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *GetSSHKey200Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into DtoSshResponse
	err = newStrictDecoder(data).Decode(&dst.DtoSshResponse)
	if err == nil {
		jsonDtoSshResponse, _ := json.Marshal(dst.DtoSshResponse)
		if string(jsonDtoSshResponse) == "{}" { // empty struct
			dst.DtoSshResponse = nil
		} else {
			if err = validator.Validate(dst.DtoSshResponse); err != nil {
				dst.DtoSshResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.DtoSshResponse = nil
	}

	// try to unmarshal data into DtoSshRevealResponse
	err = newStrictDecoder(data).Decode(&dst.DtoSshRevealResponse)
	if err == nil {
		jsonDtoSshRevealResponse, _ := json.Marshal(dst.DtoSshRevealResponse)
		if string(jsonDtoSshRevealResponse) == "{}" { // empty struct
			dst.DtoSshRevealResponse = nil
		} else {
			if err = validator.Validate(dst.DtoSshRevealResponse); err != nil {
				dst.DtoSshRevealResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.DtoSshRevealResponse = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.DtoSshResponse = nil
		dst.DtoSshRevealResponse = nil

		return fmt.Errorf("data matches more than one schema in oneOf(GetSSHKey200Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(GetSSHKey200Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetSSHKey200Response) MarshalJSON() ([]byte, error) {
	if src.DtoSshResponse != nil {
		return json.Marshal(&src.DtoSshResponse)
	}

	if src.DtoSshRevealResponse != nil {
		return json.Marshal(&src.DtoSshRevealResponse)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *GetSSHKey200Response) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.DtoSshResponse != nil {
		return obj.DtoSshResponse
	}

	if obj.DtoSshRevealResponse != nil {
		return obj.DtoSshRevealResponse
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj GetSSHKey200Response) GetActualInstanceValue() interface{} {
	if obj.DtoSshResponse != nil {
		return *obj.DtoSshResponse
	}

	if obj.DtoSshRevealResponse != nil {
		return *obj.DtoSshRevealResponse
	}

	// all schemas are nil
	return nil
}

type NullableGetSSHKey200Response struct {
	value *GetSSHKey200Response
	isSet bool
}

func (v NullableGetSSHKey200Response) Get() *GetSSHKey200Response {
	return v.value
}

func (v *NullableGetSSHKey200Response) Set(val *GetSSHKey200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSSHKey200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSSHKey200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSSHKey200Response(val *GetSSHKey200Response) *NullableGetSSHKey200Response {
	return &NullableGetSSHKey200Response{value: val, isSet: true}
}

func (v NullableGetSSHKey200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSSHKey200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
