/*
AutoGlue API

API for managing K3s clusters across cloud providers

API version: dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autoglue

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DtoCreateCredentialRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoCreateCredentialRequest{}

// DtoCreateCredentialRequest struct for DtoCreateCredentialRequest
type DtoCreateCredentialRequest struct {
	AccountId *string `json:"account_id,omitempty"`
	// aws_access_key, api_token, basic_auth, oauth2
	Kind string `json:"kind"`
	// human label
	Name     *string `json:"name,omitempty"`
	Provider string  `json:"provider"`
	Region   *string `json:"region,omitempty"`
	// secret schema version
	SchemaVersion int32 `json:"schema_version"`
	// {\"service\":\"route53\"} or {\"arn\":\"...\"}
	Scope     map[string]interface{} `json:"scope"`
	ScopeKind string                 `json:"scope_kind"`
	// scope schema version
	ScopeVersion int32 `json:"scope_version"`
	// encrypted later
	Secret map[string]interface{} `json:"secret"`
}

type _DtoCreateCredentialRequest DtoCreateCredentialRequest

// NewDtoCreateCredentialRequest instantiates a new DtoCreateCredentialRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoCreateCredentialRequest(kind string, provider string, schemaVersion int32, scope map[string]interface{}, scopeKind string, scopeVersion int32, secret map[string]interface{}) *DtoCreateCredentialRequest {
	this := DtoCreateCredentialRequest{}
	this.Kind = kind
	this.Provider = provider
	this.SchemaVersion = schemaVersion
	this.Scope = scope
	this.ScopeKind = scopeKind
	this.ScopeVersion = scopeVersion
	this.Secret = secret
	return &this
}

// NewDtoCreateCredentialRequestWithDefaults instantiates a new DtoCreateCredentialRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoCreateCredentialRequestWithDefaults() *DtoCreateCredentialRequest {
	this := DtoCreateCredentialRequest{}
	return &this
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *DtoCreateCredentialRequest) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreateCredentialRequest) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *DtoCreateCredentialRequest) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *DtoCreateCredentialRequest) SetAccountId(v string) {
	o.AccountId = &v
}

// GetKind returns the Kind field value
func (o *DtoCreateCredentialRequest) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *DtoCreateCredentialRequest) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *DtoCreateCredentialRequest) SetKind(v string) {
	o.Kind = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DtoCreateCredentialRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreateCredentialRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DtoCreateCredentialRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DtoCreateCredentialRequest) SetName(v string) {
	o.Name = &v
}

// GetProvider returns the Provider field value
func (o *DtoCreateCredentialRequest) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *DtoCreateCredentialRequest) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *DtoCreateCredentialRequest) SetProvider(v string) {
	o.Provider = v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *DtoCreateCredentialRequest) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreateCredentialRequest) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *DtoCreateCredentialRequest) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *DtoCreateCredentialRequest) SetRegion(v string) {
	o.Region = &v
}

// GetSchemaVersion returns the SchemaVersion field value
func (o *DtoCreateCredentialRequest) GetSchemaVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SchemaVersion
}

// GetSchemaVersionOk returns a tuple with the SchemaVersion field value
// and a boolean to check if the value has been set.
func (o *DtoCreateCredentialRequest) GetSchemaVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SchemaVersion, true
}

// SetSchemaVersion sets field value
func (o *DtoCreateCredentialRequest) SetSchemaVersion(v int32) {
	o.SchemaVersion = v
}

// GetScope returns the Scope field value
func (o *DtoCreateCredentialRequest) GetScope() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *DtoCreateCredentialRequest) GetScopeOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Scope, true
}

// SetScope sets field value
func (o *DtoCreateCredentialRequest) SetScope(v map[string]interface{}) {
	o.Scope = v
}

// GetScopeKind returns the ScopeKind field value
func (o *DtoCreateCredentialRequest) GetScopeKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ScopeKind
}

// GetScopeKindOk returns a tuple with the ScopeKind field value
// and a boolean to check if the value has been set.
func (o *DtoCreateCredentialRequest) GetScopeKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScopeKind, true
}

// SetScopeKind sets field value
func (o *DtoCreateCredentialRequest) SetScopeKind(v string) {
	o.ScopeKind = v
}

// GetScopeVersion returns the ScopeVersion field value
func (o *DtoCreateCredentialRequest) GetScopeVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ScopeVersion
}

// GetScopeVersionOk returns a tuple with the ScopeVersion field value
// and a boolean to check if the value has been set.
func (o *DtoCreateCredentialRequest) GetScopeVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScopeVersion, true
}

// SetScopeVersion sets field value
func (o *DtoCreateCredentialRequest) SetScopeVersion(v int32) {
	o.ScopeVersion = v
}

// GetSecret returns the Secret field value
func (o *DtoCreateCredentialRequest) GetSecret() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Secret
}

// GetSecretOk returns a tuple with the Secret field value
// and a boolean to check if the value has been set.
func (o *DtoCreateCredentialRequest) GetSecretOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Secret, true
}

// SetSecret sets field value
func (o *DtoCreateCredentialRequest) SetSecret(v map[string]interface{}) {
	o.Secret = v
}

func (o DtoCreateCredentialRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoCreateCredentialRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountId) {
		toSerialize["account_id"] = o.AccountId
	}
	toSerialize["kind"] = o.Kind
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	toSerialize["provider"] = o.Provider
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	toSerialize["schema_version"] = o.SchemaVersion
	toSerialize["scope"] = o.Scope
	toSerialize["scope_kind"] = o.ScopeKind
	toSerialize["scope_version"] = o.ScopeVersion
	toSerialize["secret"] = o.Secret
	return toSerialize, nil
}

func (o *DtoCreateCredentialRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"kind",
		"provider",
		"schema_version",
		"scope",
		"scope_kind",
		"scope_version",
		"secret",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDtoCreateCredentialRequest := _DtoCreateCredentialRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDtoCreateCredentialRequest)

	if err != nil {
		return err
	}

	*o = DtoCreateCredentialRequest(varDtoCreateCredentialRequest)

	return err
}

type NullableDtoCreateCredentialRequest struct {
	value *DtoCreateCredentialRequest
	isSet bool
}

func (v NullableDtoCreateCredentialRequest) Get() *DtoCreateCredentialRequest {
	return v.value
}

func (v *NullableDtoCreateCredentialRequest) Set(val *DtoCreateCredentialRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoCreateCredentialRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoCreateCredentialRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoCreateCredentialRequest(val *DtoCreateCredentialRequest) *NullableDtoCreateCredentialRequest {
	return &NullableDtoCreateCredentialRequest{value: val, isSet: true}
}

func (v NullableDtoCreateCredentialRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoCreateCredentialRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
