/*
AutoGlue API

API for managing K3s clusters across cloud providers

API version: dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autoglue

import (
	"encoding/json"
)

// checks if the DtoUpdateLoadBalancerRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoUpdateLoadBalancerRequest{}

// DtoUpdateLoadBalancerRequest struct for DtoUpdateLoadBalancerRequest
type DtoUpdateLoadBalancerRequest struct {
	Kind             *string `json:"kind,omitempty"`
	Name             *string `json:"name,omitempty"`
	PrivateIpAddress *string `json:"private_ip_address,omitempty"`
	PublicIpAddress  *string `json:"public_ip_address,omitempty"`
}

// NewDtoUpdateLoadBalancerRequest instantiates a new DtoUpdateLoadBalancerRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoUpdateLoadBalancerRequest() *DtoUpdateLoadBalancerRequest {
	this := DtoUpdateLoadBalancerRequest{}
	return &this
}

// NewDtoUpdateLoadBalancerRequestWithDefaults instantiates a new DtoUpdateLoadBalancerRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoUpdateLoadBalancerRequestWithDefaults() *DtoUpdateLoadBalancerRequest {
	this := DtoUpdateLoadBalancerRequest{}
	return &this
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *DtoUpdateLoadBalancerRequest) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoUpdateLoadBalancerRequest) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *DtoUpdateLoadBalancerRequest) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *DtoUpdateLoadBalancerRequest) SetKind(v string) {
	o.Kind = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DtoUpdateLoadBalancerRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoUpdateLoadBalancerRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DtoUpdateLoadBalancerRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DtoUpdateLoadBalancerRequest) SetName(v string) {
	o.Name = &v
}

// GetPrivateIpAddress returns the PrivateIpAddress field value if set, zero value otherwise.
func (o *DtoUpdateLoadBalancerRequest) GetPrivateIpAddress() string {
	if o == nil || IsNil(o.PrivateIpAddress) {
		var ret string
		return ret
	}
	return *o.PrivateIpAddress
}

// GetPrivateIpAddressOk returns a tuple with the PrivateIpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoUpdateLoadBalancerRequest) GetPrivateIpAddressOk() (*string, bool) {
	if o == nil || IsNil(o.PrivateIpAddress) {
		return nil, false
	}
	return o.PrivateIpAddress, true
}

// HasPrivateIpAddress returns a boolean if a field has been set.
func (o *DtoUpdateLoadBalancerRequest) HasPrivateIpAddress() bool {
	if o != nil && !IsNil(o.PrivateIpAddress) {
		return true
	}

	return false
}

// SetPrivateIpAddress gets a reference to the given string and assigns it to the PrivateIpAddress field.
func (o *DtoUpdateLoadBalancerRequest) SetPrivateIpAddress(v string) {
	o.PrivateIpAddress = &v
}

// GetPublicIpAddress returns the PublicIpAddress field value if set, zero value otherwise.
func (o *DtoUpdateLoadBalancerRequest) GetPublicIpAddress() string {
	if o == nil || IsNil(o.PublicIpAddress) {
		var ret string
		return ret
	}
	return *o.PublicIpAddress
}

// GetPublicIpAddressOk returns a tuple with the PublicIpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoUpdateLoadBalancerRequest) GetPublicIpAddressOk() (*string, bool) {
	if o == nil || IsNil(o.PublicIpAddress) {
		return nil, false
	}
	return o.PublicIpAddress, true
}

// HasPublicIpAddress returns a boolean if a field has been set.
func (o *DtoUpdateLoadBalancerRequest) HasPublicIpAddress() bool {
	if o != nil && !IsNil(o.PublicIpAddress) {
		return true
	}

	return false
}

// SetPublicIpAddress gets a reference to the given string and assigns it to the PublicIpAddress field.
func (o *DtoUpdateLoadBalancerRequest) SetPublicIpAddress(v string) {
	o.PublicIpAddress = &v
}

func (o DtoUpdateLoadBalancerRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoUpdateLoadBalancerRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.PrivateIpAddress) {
		toSerialize["private_ip_address"] = o.PrivateIpAddress
	}
	if !IsNil(o.PublicIpAddress) {
		toSerialize["public_ip_address"] = o.PublicIpAddress
	}
	return toSerialize, nil
}

type NullableDtoUpdateLoadBalancerRequest struct {
	value *DtoUpdateLoadBalancerRequest
	isSet bool
}

func (v NullableDtoUpdateLoadBalancerRequest) Get() *DtoUpdateLoadBalancerRequest {
	return v.value
}

func (v *NullableDtoUpdateLoadBalancerRequest) Set(val *DtoUpdateLoadBalancerRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoUpdateLoadBalancerRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoUpdateLoadBalancerRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoUpdateLoadBalancerRequest(val *DtoUpdateLoadBalancerRequest) *NullableDtoUpdateLoadBalancerRequest {
	return &NullableDtoUpdateLoadBalancerRequest{value: val, isSet: true}
}

func (v NullableDtoUpdateLoadBalancerRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoUpdateLoadBalancerRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
