/*
AutoGlue API

API for managing K3s clusters across cloud providers

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autoglue

import (
	"encoding/json"
)

// checks if the DtoCreateNodePoolRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoCreateNodePoolRequest{}

// DtoCreateNodePoolRequest struct for DtoCreateNodePoolRequest
type DtoCreateNodePoolRequest struct {
	Name *string `json:"name,omitempty"`
	Role *string `json:"role,omitempty"`
}

// NewDtoCreateNodePoolRequest instantiates a new DtoCreateNodePoolRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoCreateNodePoolRequest() *DtoCreateNodePoolRequest {
	this := DtoCreateNodePoolRequest{}
	return &this
}

// NewDtoCreateNodePoolRequestWithDefaults instantiates a new DtoCreateNodePoolRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoCreateNodePoolRequestWithDefaults() *DtoCreateNodePoolRequest {
	this := DtoCreateNodePoolRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DtoCreateNodePoolRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreateNodePoolRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DtoCreateNodePoolRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DtoCreateNodePoolRequest) SetName(v string) {
	o.Name = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *DtoCreateNodePoolRequest) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreateNodePoolRequest) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *DtoCreateNodePoolRequest) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *DtoCreateNodePoolRequest) SetRole(v string) {
	o.Role = &v
}

func (o DtoCreateNodePoolRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoCreateNodePoolRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	return toSerialize, nil
}

type NullableDtoCreateNodePoolRequest struct {
	value *DtoCreateNodePoolRequest
	isSet bool
}

func (v NullableDtoCreateNodePoolRequest) Get() *DtoCreateNodePoolRequest {
	return v.value
}

func (v *NullableDtoCreateNodePoolRequest) Set(val *DtoCreateNodePoolRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoCreateNodePoolRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoCreateNodePoolRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoCreateNodePoolRequest(val *DtoCreateNodePoolRequest) *NullableDtoCreateNodePoolRequest {
	return &NullableDtoCreateNodePoolRequest{value: val, isSet: true}
}

func (v NullableDtoCreateNodePoolRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoCreateNodePoolRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
