/*
AutoGlue API

API for managing K3s clusters across cloud providers

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autoglue

import (
	"encoding/json"
)

// checks if the HandlersHealthStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HandlersHealthStatus{}

// HandlersHealthStatus struct for HandlersHealthStatus
type HandlersHealthStatus struct {
	Status *string `json:"status,omitempty"`
}

// NewHandlersHealthStatus instantiates a new HandlersHealthStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHandlersHealthStatus() *HandlersHealthStatus {
	this := HandlersHealthStatus{}
	return &this
}

// NewHandlersHealthStatusWithDefaults instantiates a new HandlersHealthStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHandlersHealthStatusWithDefaults() *HandlersHealthStatus {
	this := HandlersHealthStatus{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *HandlersHealthStatus) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlersHealthStatus) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *HandlersHealthStatus) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *HandlersHealthStatus) SetStatus(v string) {
	o.Status = &v
}

func (o HandlersHealthStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HandlersHealthStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableHandlersHealthStatus struct {
	value *HandlersHealthStatus
	isSet bool
}

func (v NullableHandlersHealthStatus) Get() *HandlersHealthStatus {
	return v.value
}

func (v *NullableHandlersHealthStatus) Set(val *HandlersHealthStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableHandlersHealthStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableHandlersHealthStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHandlersHealthStatus(val *HandlersHealthStatus) *NullableHandlersHealthStatus {
	return &NullableHandlersHealthStatus{value: val, isSet: true}
}

func (v NullableHandlersHealthStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHandlersHealthStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
