/*
AutoGlue API

API for managing K3s clusters across cloud providers

API version: dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autoglue

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DtoCreateDomainRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoCreateDomainRequest{}

// DtoCreateDomainRequest struct for DtoCreateDomainRequest
type DtoCreateDomainRequest struct {
	CredentialId string  `json:"credential_id"`
	DomainName   string  `json:"domain_name"`
	ZoneId       *string `json:"zone_id,omitempty"`
}

type _DtoCreateDomainRequest DtoCreateDomainRequest

// NewDtoCreateDomainRequest instantiates a new DtoCreateDomainRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoCreateDomainRequest(credentialId string, domainName string) *DtoCreateDomainRequest {
	this := DtoCreateDomainRequest{}
	this.CredentialId = credentialId
	this.DomainName = domainName
	return &this
}

// NewDtoCreateDomainRequestWithDefaults instantiates a new DtoCreateDomainRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoCreateDomainRequestWithDefaults() *DtoCreateDomainRequest {
	this := DtoCreateDomainRequest{}
	return &this
}

// GetCredentialId returns the CredentialId field value
func (o *DtoCreateDomainRequest) GetCredentialId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CredentialId
}

// GetCredentialIdOk returns a tuple with the CredentialId field value
// and a boolean to check if the value has been set.
func (o *DtoCreateDomainRequest) GetCredentialIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CredentialId, true
}

// SetCredentialId sets field value
func (o *DtoCreateDomainRequest) SetCredentialId(v string) {
	o.CredentialId = v
}

// GetDomainName returns the DomainName field value
func (o *DtoCreateDomainRequest) GetDomainName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DomainName
}

// GetDomainNameOk returns a tuple with the DomainName field value
// and a boolean to check if the value has been set.
func (o *DtoCreateDomainRequest) GetDomainNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DomainName, true
}

// SetDomainName sets field value
func (o *DtoCreateDomainRequest) SetDomainName(v string) {
	o.DomainName = v
}

// GetZoneId returns the ZoneId field value if set, zero value otherwise.
func (o *DtoCreateDomainRequest) GetZoneId() string {
	if o == nil || IsNil(o.ZoneId) {
		var ret string
		return ret
	}
	return *o.ZoneId
}

// GetZoneIdOk returns a tuple with the ZoneId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreateDomainRequest) GetZoneIdOk() (*string, bool) {
	if o == nil || IsNil(o.ZoneId) {
		return nil, false
	}
	return o.ZoneId, true
}

// HasZoneId returns a boolean if a field has been set.
func (o *DtoCreateDomainRequest) HasZoneId() bool {
	if o != nil && !IsNil(o.ZoneId) {
		return true
	}

	return false
}

// SetZoneId gets a reference to the given string and assigns it to the ZoneId field.
func (o *DtoCreateDomainRequest) SetZoneId(v string) {
	o.ZoneId = &v
}

func (o DtoCreateDomainRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoCreateDomainRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["credential_id"] = o.CredentialId
	toSerialize["domain_name"] = o.DomainName
	if !IsNil(o.ZoneId) {
		toSerialize["zone_id"] = o.ZoneId
	}
	return toSerialize, nil
}

func (o *DtoCreateDomainRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"credential_id",
		"domain_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDtoCreateDomainRequest := _DtoCreateDomainRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDtoCreateDomainRequest)

	if err != nil {
		return err
	}

	*o = DtoCreateDomainRequest(varDtoCreateDomainRequest)

	return err
}

type NullableDtoCreateDomainRequest struct {
	value *DtoCreateDomainRequest
	isSet bool
}

func (v NullableDtoCreateDomainRequest) Get() *DtoCreateDomainRequest {
	return v.value
}

func (v *NullableDtoCreateDomainRequest) Set(val *DtoCreateDomainRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoCreateDomainRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoCreateDomainRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoCreateDomainRequest(val *DtoCreateDomainRequest) *NullableDtoCreateDomainRequest {
	return &NullableDtoCreateDomainRequest{value: val, isSet: true}
}

func (v NullableDtoCreateDomainRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoCreateDomainRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
