/*
AutoGlue API

API for managing K3s clusters across cloud providers

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autoglue

import (
	"encoding/json"
)

// checks if the DtoUpdateTaintRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoUpdateTaintRequest{}

// DtoUpdateTaintRequest struct for DtoUpdateTaintRequest
type DtoUpdateTaintRequest struct {
	Effect *string `json:"effect,omitempty"`
	Key    *string `json:"key,omitempty"`
	Value  *string `json:"value,omitempty"`
}

// NewDtoUpdateTaintRequest instantiates a new DtoUpdateTaintRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoUpdateTaintRequest() *DtoUpdateTaintRequest {
	this := DtoUpdateTaintRequest{}
	return &this
}

// NewDtoUpdateTaintRequestWithDefaults instantiates a new DtoUpdateTaintRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoUpdateTaintRequestWithDefaults() *DtoUpdateTaintRequest {
	this := DtoUpdateTaintRequest{}
	return &this
}

// GetEffect returns the Effect field value if set, zero value otherwise.
func (o *DtoUpdateTaintRequest) GetEffect() string {
	if o == nil || IsNil(o.Effect) {
		var ret string
		return ret
	}
	return *o.Effect
}

// GetEffectOk returns a tuple with the Effect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoUpdateTaintRequest) GetEffectOk() (*string, bool) {
	if o == nil || IsNil(o.Effect) {
		return nil, false
	}
	return o.Effect, true
}

// HasEffect returns a boolean if a field has been set.
func (o *DtoUpdateTaintRequest) HasEffect() bool {
	if o != nil && !IsNil(o.Effect) {
		return true
	}

	return false
}

// SetEffect gets a reference to the given string and assigns it to the Effect field.
func (o *DtoUpdateTaintRequest) SetEffect(v string) {
	o.Effect = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *DtoUpdateTaintRequest) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoUpdateTaintRequest) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *DtoUpdateTaintRequest) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *DtoUpdateTaintRequest) SetKey(v string) {
	o.Key = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *DtoUpdateTaintRequest) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoUpdateTaintRequest) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *DtoUpdateTaintRequest) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *DtoUpdateTaintRequest) SetValue(v string) {
	o.Value = &v
}

func (o DtoUpdateTaintRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoUpdateTaintRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Effect) {
		toSerialize["effect"] = o.Effect
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableDtoUpdateTaintRequest struct {
	value *DtoUpdateTaintRequest
	isSet bool
}

func (v NullableDtoUpdateTaintRequest) Get() *DtoUpdateTaintRequest {
	return v.value
}

func (v *NullableDtoUpdateTaintRequest) Set(val *DtoUpdateTaintRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoUpdateTaintRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoUpdateTaintRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoUpdateTaintRequest(val *DtoUpdateTaintRequest) *NullableDtoUpdateTaintRequest {
	return &NullableDtoUpdateTaintRequest{value: val, isSet: true}
}

func (v NullableDtoUpdateTaintRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoUpdateTaintRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
