/*
AutoGlue API

API for managing K3s clusters across cloud providers

API version: dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autoglue

import (
	"encoding/json"
)

// checks if the DtoUpdateClusterRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoUpdateClusterRequest{}

// DtoUpdateClusterRequest struct for DtoUpdateClusterRequest
type DtoUpdateClusterRequest struct {
	Name     *string `json:"name,omitempty"`
	Provider *string `json:"provider,omitempty"`
	Region   *string `json:"region,omitempty"`
}

// NewDtoUpdateClusterRequest instantiates a new DtoUpdateClusterRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoUpdateClusterRequest() *DtoUpdateClusterRequest {
	this := DtoUpdateClusterRequest{}
	return &this
}

// NewDtoUpdateClusterRequestWithDefaults instantiates a new DtoUpdateClusterRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoUpdateClusterRequestWithDefaults() *DtoUpdateClusterRequest {
	this := DtoUpdateClusterRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DtoUpdateClusterRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoUpdateClusterRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DtoUpdateClusterRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DtoUpdateClusterRequest) SetName(v string) {
	o.Name = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *DtoUpdateClusterRequest) GetProvider() string {
	if o == nil || IsNil(o.Provider) {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoUpdateClusterRequest) GetProviderOk() (*string, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *DtoUpdateClusterRequest) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *DtoUpdateClusterRequest) SetProvider(v string) {
	o.Provider = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *DtoUpdateClusterRequest) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoUpdateClusterRequest) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *DtoUpdateClusterRequest) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *DtoUpdateClusterRequest) SetRegion(v string) {
	o.Region = &v
}

func (o DtoUpdateClusterRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoUpdateClusterRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	return toSerialize, nil
}

type NullableDtoUpdateClusterRequest struct {
	value *DtoUpdateClusterRequest
	isSet bool
}

func (v NullableDtoUpdateClusterRequest) Get() *DtoUpdateClusterRequest {
	return v.value
}

func (v *NullableDtoUpdateClusterRequest) Set(val *DtoUpdateClusterRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoUpdateClusterRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoUpdateClusterRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoUpdateClusterRequest(val *DtoUpdateClusterRequest) *NullableDtoUpdateClusterRequest {
	return &NullableDtoUpdateClusterRequest{value: val, isSet: true}
}

func (v NullableDtoUpdateClusterRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoUpdateClusterRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
