/*
AutoGlue API

API for managing K3s clusters across cloud providers

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autoglue

import (
	"encoding/json"
)

// checks if the DtoAuthStartResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoAuthStartResponse{}

// DtoAuthStartResponse struct for DtoAuthStartResponse
type DtoAuthStartResponse struct {
	AuthUrl *string `json:"auth_url,omitempty"`
}

// NewDtoAuthStartResponse instantiates a new DtoAuthStartResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoAuthStartResponse() *DtoAuthStartResponse {
	this := DtoAuthStartResponse{}
	return &this
}

// NewDtoAuthStartResponseWithDefaults instantiates a new DtoAuthStartResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoAuthStartResponseWithDefaults() *DtoAuthStartResponse {
	this := DtoAuthStartResponse{}
	return &this
}

// GetAuthUrl returns the AuthUrl field value if set, zero value otherwise.
func (o *DtoAuthStartResponse) GetAuthUrl() string {
	if o == nil || IsNil(o.AuthUrl) {
		var ret string
		return ret
	}
	return *o.AuthUrl
}

// GetAuthUrlOk returns a tuple with the AuthUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoAuthStartResponse) GetAuthUrlOk() (*string, bool) {
	if o == nil || IsNil(o.AuthUrl) {
		return nil, false
	}
	return o.AuthUrl, true
}

// HasAuthUrl returns a boolean if a field has been set.
func (o *DtoAuthStartResponse) HasAuthUrl() bool {
	if o != nil && !IsNil(o.AuthUrl) {
		return true
	}

	return false
}

// SetAuthUrl gets a reference to the given string and assigns it to the AuthUrl field.
func (o *DtoAuthStartResponse) SetAuthUrl(v string) {
	o.AuthUrl = &v
}

func (o DtoAuthStartResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoAuthStartResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AuthUrl) {
		toSerialize["auth_url"] = o.AuthUrl
	}
	return toSerialize, nil
}

type NullableDtoAuthStartResponse struct {
	value *DtoAuthStartResponse
	isSet bool
}

func (v NullableDtoAuthStartResponse) Get() *DtoAuthStartResponse {
	return v.value
}

func (v *NullableDtoAuthStartResponse) Set(val *DtoAuthStartResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoAuthStartResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoAuthStartResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoAuthStartResponse(val *DtoAuthStartResponse) *NullableDtoAuthStartResponse {
	return &NullableDtoAuthStartResponse{value: val, isSet: true}
}

func (v NullableDtoAuthStartResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoAuthStartResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
