/*
AutoGlue API

API for managing K3s clusters across cloud providers

API version: dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autoglue

import (
	"encoding/json"
)

// checks if the DtoUpdateDomainRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoUpdateDomainRequest{}

// DtoUpdateDomainRequest struct for DtoUpdateDomainRequest
type DtoUpdateDomainRequest struct {
	CredentialId *string `json:"credential_id,omitempty"`
	DomainName   *string `json:"domain_name,omitempty"`
	Status       *string `json:"status,omitempty"`
	ZoneId       *string `json:"zone_id,omitempty"`
}

// NewDtoUpdateDomainRequest instantiates a new DtoUpdateDomainRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoUpdateDomainRequest() *DtoUpdateDomainRequest {
	this := DtoUpdateDomainRequest{}
	return &this
}

// NewDtoUpdateDomainRequestWithDefaults instantiates a new DtoUpdateDomainRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoUpdateDomainRequestWithDefaults() *DtoUpdateDomainRequest {
	this := DtoUpdateDomainRequest{}
	return &this
}

// GetCredentialId returns the CredentialId field value if set, zero value otherwise.
func (o *DtoUpdateDomainRequest) GetCredentialId() string {
	if o == nil || IsNil(o.CredentialId) {
		var ret string
		return ret
	}
	return *o.CredentialId
}

// GetCredentialIdOk returns a tuple with the CredentialId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoUpdateDomainRequest) GetCredentialIdOk() (*string, bool) {
	if o == nil || IsNil(o.CredentialId) {
		return nil, false
	}
	return o.CredentialId, true
}

// HasCredentialId returns a boolean if a field has been set.
func (o *DtoUpdateDomainRequest) HasCredentialId() bool {
	if o != nil && !IsNil(o.CredentialId) {
		return true
	}

	return false
}

// SetCredentialId gets a reference to the given string and assigns it to the CredentialId field.
func (o *DtoUpdateDomainRequest) SetCredentialId(v string) {
	o.CredentialId = &v
}

// GetDomainName returns the DomainName field value if set, zero value otherwise.
func (o *DtoUpdateDomainRequest) GetDomainName() string {
	if o == nil || IsNil(o.DomainName) {
		var ret string
		return ret
	}
	return *o.DomainName
}

// GetDomainNameOk returns a tuple with the DomainName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoUpdateDomainRequest) GetDomainNameOk() (*string, bool) {
	if o == nil || IsNil(o.DomainName) {
		return nil, false
	}
	return o.DomainName, true
}

// HasDomainName returns a boolean if a field has been set.
func (o *DtoUpdateDomainRequest) HasDomainName() bool {
	if o != nil && !IsNil(o.DomainName) {
		return true
	}

	return false
}

// SetDomainName gets a reference to the given string and assigns it to the DomainName field.
func (o *DtoUpdateDomainRequest) SetDomainName(v string) {
	o.DomainName = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DtoUpdateDomainRequest) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoUpdateDomainRequest) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DtoUpdateDomainRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *DtoUpdateDomainRequest) SetStatus(v string) {
	o.Status = &v
}

// GetZoneId returns the ZoneId field value if set, zero value otherwise.
func (o *DtoUpdateDomainRequest) GetZoneId() string {
	if o == nil || IsNil(o.ZoneId) {
		var ret string
		return ret
	}
	return *o.ZoneId
}

// GetZoneIdOk returns a tuple with the ZoneId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoUpdateDomainRequest) GetZoneIdOk() (*string, bool) {
	if o == nil || IsNil(o.ZoneId) {
		return nil, false
	}
	return o.ZoneId, true
}

// HasZoneId returns a boolean if a field has been set.
func (o *DtoUpdateDomainRequest) HasZoneId() bool {
	if o != nil && !IsNil(o.ZoneId) {
		return true
	}

	return false
}

// SetZoneId gets a reference to the given string and assigns it to the ZoneId field.
func (o *DtoUpdateDomainRequest) SetZoneId(v string) {
	o.ZoneId = &v
}

func (o DtoUpdateDomainRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoUpdateDomainRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CredentialId) {
		toSerialize["credential_id"] = o.CredentialId
	}
	if !IsNil(o.DomainName) {
		toSerialize["domain_name"] = o.DomainName
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.ZoneId) {
		toSerialize["zone_id"] = o.ZoneId
	}
	return toSerialize, nil
}

type NullableDtoUpdateDomainRequest struct {
	value *DtoUpdateDomainRequest
	isSet bool
}

func (v NullableDtoUpdateDomainRequest) Get() *DtoUpdateDomainRequest {
	return v.value
}

func (v *NullableDtoUpdateDomainRequest) Set(val *DtoUpdateDomainRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoUpdateDomainRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoUpdateDomainRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoUpdateDomainRequest(val *DtoUpdateDomainRequest) *NullableDtoUpdateDomainRequest {
	return &NullableDtoUpdateDomainRequest{value: val, isSet: true}
}

func (v NullableDtoUpdateDomainRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoUpdateDomainRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
